import React from 'react';
import { FiFileText, FiUser, FiCalendar } from 'react-icons/fi';

const ReportHeader = ({ generatedBy, generatedDate, period }) => {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <FiFileText className="w-7 h-7 text-blue-600" />
            Inventory Report
          </h1>
        </div>
        <div className="flex flex-wrap gap-6 text-sm text-gray-500">
          <div className="flex items-center gap-2">
            <FiUser className="w-4 h-4" />
            <span>Generated by: <span className="font-medium text-gray-900">{generatedBy}</span></span>
          </div>
          <div className="flex items-center gap-2">
            <FiCalendar className="w-4 h-4" />
            <span>Date: <span className="font-medium text-gray-900">{generatedDate}</span></span>
          </div>
          {period && (
            <div className="flex items-center gap-2">
              <FiCalendar className="w-4 h-4" />
              <span>Period: <span className="font-medium text-gray-900">{period}</span></span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportHeader;